### ISSUE TITLE
exit codes

### ISSUE THREAD

**Issue by maany** [simple-framework/simple_bash_cli#8]
@maarten-litmaath , the exit codes at these lines:
https://github.com/simple-framework/simple_bash_cli/blob/9e58818bde31bbbcc0dac4dacf92c814d90708f5/simple#L79
should it be non-zero?

**Comment by maarten-litmaath** [comment]
By default, the exit command will propagate the exit code of the preceding command.
That is, these 2 versions are equivalent:

    exit
    exit $?
